---
title: "Job Data Visualization in R"
editor: visual
format:
  html:
    toc: true
    embed-resources: true
execute:
  echo: true
---

```{r}
library(plotly)
library(tidyverse)
library(ggplot2)
library(tidyr)
library(htmlwidgets)
library(dplyr)
options(warn = - 1)
library(withr)
library(scales)
# lubridate, zoo, xts
options(scipen=999)
library(reshape2)
```

```{r}
jobs_df <- read_csv('../../data/job_data.csv')
```

```{r}
head(jobs_df)
```
```{r}
# create a new column 'experience_group' based on 'experience'
jobs_df$experience_group <- cut(jobs_df$experience, c(0, 5, 10, Inf),
                                 labels = c('0-5', '5-10', '10+'))

```

```{r}
jobs_df_pivot <- jobs_df %>%
  group_by(degree, experience_group) %>%
  summarise(mean_salary = mean(salary, na.rm = TRUE)) %>%
  pivot_wider(names_from = experience_group, values_from = mean_salary)
```
```{r}
jobs_df_pivot <- jobs_df_pivot[1:(nrow(jobs_df_pivot)-1), 1:(ncol(jobs_df_pivot)-1)]

```



```{r}
ap <- jobs_df_pivot %>% plot_ly(
    hovertext = "Degree, Salary"
) #text = list('15.7%'))
ap <- ap %>%
  add_trace(x = jobs_df_pivot$degree, y = ~`0-5`, type = 'bar', name = '0-5', marker = list(color = '#118C4F'))

ap <- ap %>%
  add_trace(x = jobs_df_pivot$degree, y = ~`5-10`, type = 'bar', name = '5-10', marker = list(color = '#FFB90D'))
ap <- ap %>%
  add_trace(x = jobs_df_pivot$degree, y = ~`10+`, type = 'bar', name = '10+' , marker = list(color = 'red'))
#hovertemplate = paste('<i>Price</i>: $%{top5:.2f}',
#                        '<br><b>X</b>: %year<br>',
#                        '<b>%{text}</b>'))


f <- list(
  family = "Arial",
  size = 18,
  color = "black")
f1 <- list(
  title = "Degree",
  titlefont = "Arial")
f2 <- list(
  title = "Salary (USD)",
  titlefont = "Arial")
f3 <- list(
  family = "Arial",
  size = 18,
  color = "black")

ap <- ap %>% layout(xaxis = f1, yaxis = f2)
ap <- ap %>% layout(title= list(text = "", y = 0.98, font = f3))
ap <- ap %>% layout(legend=list(title=list(text='Years of Experience')))
ap
```

```{r}

# Select the top 15 companies by job count
top_companies <- jobs_df %>%
  filter(company_name != "Unknown") %>%
  group_by(company_name) %>%
  summarise(n_jobs = n()) %>%
  ungroup() %>%
  top_n(15, n_jobs) %>%
  arrange(desc(n_jobs))

# Select the jobs that belong to the top companies
jobs_top_companies <- jobs_df %>%
  filter(company_name %in% top_companies$company_name) %>%
  select(query, company_name)

# Create a matrix of the number of jobs for each combination of query and company_name
jobs_matrix <- table(jobs_top_companies)

# Create the chord diagram
chord <- plot_ly(type = "choropleth",
                 locations = top_companies$company_name,
                 locationmode = "USA-states",
                 z = top_companies$n_jobs,
                 text = top_companies$company_name,
                 colorscale = "Viridis",
                 zmin = 0, zmax = max(top_companies$n_jobs)) %>%
  add_trace(type = "sankey",
            source = rep(0:nrow(top_companies)-1, nrow(top_companies)),
            target = as.vector(outer(0:nrow(top_companies)-1, 0:nrow(top_companies)-1, FUN = "+")),
            value = as.vector(jobs_matrix),
            node = list(label = c("All queries", top_companies$company_name),
                        pad = 10,
                        thickness = 10,
                        line = list(color = "black", width = 0.5),
                        x = c(rep(0, nrow(top_companies)), rep(1, nrow(top_companies)))),
            link = list(source = as.vector(col(jobs_matrix)),
                        target = as.vector(row(jobs_matrix)),
                        value = as.vector(jobs_matrix))) %>%
  layout(title = "Chord Diagram of Job Queries and Top 15 Companies",
         font = list(family = "Arial, sans-serif"),
         width = 800, height = 800,
         margin = list(l = 100, r = 100, b = 100, t = 100),
         paper_bgcolor = "white",
         plot_bgcolor = "white",
         xaxis = list(title = ""),
         yaxis = list(title = ""))
chord

```

